jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # --- Backend ---
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend server
        working-directory: ./backend
        run: npm run dev
        # يمكنك تعليق هذه الخطوة أثناء CI إذا لا تريد تشغيل السيرفر

      # --- Frontend ---
      - name: Install frontend dependencies
        working-directory: ./frontend-website
        run: npm install

      # في Vanilla JS، لا يوجد build، فقط نتحقق أن dependencies تثبتت
